#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed gimp tldr go nodejs npm fzf rofi-wayland waybar go

sudo pacman -S --noconfirm ttf-jetbrains-mono-nerd ttf-font-awesome ttf-nerd-fonts-symbols

sudo pacman -S --noconfirm --needed hyprlock

paru -Syu wlogout-git --noconfirm --needed
